# Generated by Django 4.2.26 on 2025-12-03 16:03

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("paypal", "PayPal"),
                            ("mtn_momo", "MTN Mobile Money"),
                            ("bank_transfer", "Virement Bancaire"),
                            ("credit_card", "Carte de Crédit"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_automatic",
                    models.BooleanField(
                        default=False, help_text="Paiement automatique ou manuel"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("monthly_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("yearly_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "max_esxi_servers",
                    models.IntegerField(help_text="Nombre max de serveurs ESXi"),
                ),
                ("max_vms", models.IntegerField(help_text="Nombre max de VMs")),
                (
                    "max_backups_per_month",
                    models.IntegerField(help_text="Nombre max de sauvegardes/mois"),
                ),
                ("max_storage_gb", models.IntegerField(help_text="Stockage max en GB")),
                (
                    "max_users",
                    models.IntegerField(
                        help_text="Nombre max d'utilisateurs par organisation"
                    ),
                ),
                ("has_replication", models.BooleanField(default=False)),
                ("has_surebackup", models.BooleanField(default=False)),
                ("has_email_notifications", models.BooleanField(default=True)),
                ("has_advanced_monitoring", models.BooleanField(default=False)),
                ("has_api_access", models.BooleanField(default=False)),
                ("has_priority_support", models.BooleanField(default=False)),
                ("snapshot_retention_days", models.IntegerField(default=7)),
                ("backup_retention_days", models.IntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["monthly_price"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Nom de l'organisation", max_length=255),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identifiant unique (URL)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En Attente"),
                            ("active", "Actif"),
                            ("suspended", "Suspendu"),
                            ("cancelled", "Annulé"),
                            ("expired", "Expiré"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("subscription_start", models.DateTimeField(blank=True, null=True)),
                ("subscription_end", models.DateTimeField(blank=True, null=True)),
                ("is_trial", models.BooleanField(default=False)),
                ("trial_end", models.DateTimeField(blank=True, null=True)),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Mensuel"), ("yearly", "Annuel")],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("next_billing_date", models.DateField(blank=True, null=True)),
                ("auto_renew", models.BooleanField(default=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provisioned_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de provisionnement automatique",
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organizations",
                        to="tenants.plan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Mensuel"), ("yearly", "Annuel")],
                        max_length=20,
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="XAF", max_length=3)),
                ("payment_status", models.CharField(default="pending", max_length=20)),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="Transaction ID from payment provider",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En Attente"),
                            ("payment_pending", "Paiement en Attente"),
                            ("paid", "Payé"),
                            ("processing", "En Traitement"),
                            ("completed", "Terminé"),
                            ("failed", "Échoué"),
                            ("cancelled", "Annulé"),
                            ("refunded", "Remboursé"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_phone", models.CharField(blank=True, max_length=50)),
                ("provisioned_at", models.DateTimeField(blank=True, null=True)),
                ("provisioning_error", models.TextField(blank=True)),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Notes internes admin"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="tenants.organization",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenants.paymentmethod",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenants.plan"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField()),
                ("paid_date", models.DateField(blank=True, null=True)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="XAF", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("sent", "Envoyé"),
                            ("paid", "Payé"),
                            ("overdue", "En Retard"),
                            ("cancelled", "Annulé"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="invoices/"),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice",
                        to="tenants.order",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="tenants.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Pourcentage"),
                            ("fixed", "Montant Fixe"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "max_uses",
                    models.IntegerField(
                        blank=True,
                        help_text="Nombre max d'utilisations (null = illimité)",
                        null=True,
                    ),
                ),
                ("uses_count", models.IntegerField(default=0)),
                ("max_uses_per_user", models.IntegerField(default=1)),
                (
                    "minimum_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicable_plans",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Plans éligibles (vide = tous)",
                        to="tenants.plan",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsageMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("esxi_servers_count", models.IntegerField(default=0)),
                ("vms_count", models.IntegerField(default=0)),
                ("backups_count", models.IntegerField(default=0)),
                ("storage_used_gb", models.FloatField(default=0.0)),
                ("users_count", models.IntegerField(default=0)),
                ("replications_count", models.IntegerField(default=0)),
                ("surebackup_verifications_count", models.IntegerField(default=0)),
                ("api_calls_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_metrics",
                        to="tenants.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start"],
                "indexes": [
                    models.Index(
                        fields=["organization", "period_start"],
                        name="tenants_usa_organiz_9f006f_idx",
                    )
                ],
                "unique_together": {("organization", "period_start")},
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=255, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="XAF", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En Attente"),
                            ("processing", "En Traitement"),
                            ("completed", "Terminé"),
                            ("failed", "Échoué"),
                            ("cancelled", "Annulé"),
                            ("refunded", "Remboursé"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "provider_transaction_id",
                    models.CharField(
                        blank=True, help_text="ID from payment provider", max_length=255
                    ),
                ),
                (
                    "provider_response",
                    models.JSONField(
                        blank=True, default=dict, help_text="Raw response from provider"
                    ),
                ),
                ("bank_reference", models.CharField(blank=True, max_length=255)),
                (
                    "bank_receipt",
                    models.FileField(
                        blank=True, null=True, upload_to="payment_receipts/"
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="tenants.order",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="tenants.organization",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenants.paymentmethod",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["transaction_id"], name="tenants_pay_transac_fd784c_idx"
                    ),
                    models.Index(
                        fields=["status"], name="tenants_pay_status_6a390d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganizationMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Propriétaire"),
                            ("admin", "Administrateur"),
                            ("member", "Membre"),
                            ("viewer", "Observateur"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invited_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="tenants.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-invited_at"],
                "unique_together": {("organization", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["slug"], name="tenants_org_slug_3f63d7_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["status"], name="tenants_org_status_134ebb_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_number"], name="tenants_ord_order_n_902449_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="tenants_ord_status_c32659_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["payment_status"], name="tenants_ord_payment_fe576d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_number"], name="tenants_inv_invoice_b03261_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="tenants_inv_status_8ea065_idx"),
        ),
    ]
