# Generated by Django 4.2.26 on 2025-11-18 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0007_add_error_message_to_backup_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='base_backup',
            field=models.ForeignKey(blank=True, help_text='Référence à la sauvegarde de base (pour les sauvegardes incrémentales)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incremental_backups', to='backups.backupjob'),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='change_id',
            field=models.CharField(blank=True, help_text='CBT Change ID pour suivre les modifications', max_length=255),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='is_cbt_enabled',
            field=models.BooleanField(default=False, help_text='Indique si CBT était activé lors de cette sauvegarde'),
        ),
        migrations.AlterField(
            model_name='backupjob',
            name='backup_mode',
            field=models.CharField(choices=[('ovf', 'OVF Export (Standard format - Restorable)'), ('cbt', 'CBT Incremental (Changed Block Tracking)')], default='ovf', max_length=50),
        ),
    ]
