# Generated by Django 5.1.5 on 2025-11-18 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0011_add_intelligent_scheduling'),
        ('esxi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom descriptif de la notification (ex: 'Email Admin - Erreurs')", max_length=255)),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook'), ('slack', 'Slack'), ('teams', 'Microsoft Teams')], default='email', help_text='Type de notification', max_length=50)),
                ('event_types', models.JSONField(default=list, help_text="Liste des événements à surveiller (ex: ['backup_failure', 'storage_full'])")),
                ('is_enabled', models.BooleanField(default=True, help_text='Activer/désactiver cette notification')),
                ('email_recipients', models.TextField(blank=True, help_text='Adresses email séparées par des virgules')),
                ('email_subject_template', models.CharField(blank=True, default='[ESXi Backup] {event_type} - {vm_name}', help_text="Template du sujet de l'email (variables: {event_type}, {vm_name}, {status})", max_length=255)),
                ('webhook_url', models.URLField(blank=True, help_text='URL du webhook (ex: https://hooks.slack.com/services/...)')),
                ('webhook_headers', models.JSONField(blank=True, default=dict, help_text='Headers HTTP personnalisés pour le webhook (JSON)')),
                ('webhook_method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT')], default='POST', help_text='Méthode HTTP', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_configs', to=settings.AUTH_USER_MODEL)),
                ('filter_schedules', models.ManyToManyField(blank=True, help_text='Filtrer par schedules spécifiques', related_name='notification_configs', to='backups.backupschedule')),
                ('filter_vms', models.ManyToManyField(blank=True, help_text='Filtrer par VMs spécifiques (vide = toutes les VMs)', related_name='notification_configs', to='esxi.virtualmachine')),
            ],
            options={
                'verbose_name': 'Notification Configuration',
                'verbose_name_plural': 'Notification Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text="Type d'événement qui a déclenché la notification", max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=50)),
                ('subject', models.CharField(blank=True, help_text='Sujet de la notification (email)', max_length=500)),
                ('message', models.TextField(help_text='Contenu de la notification')),
                ('recipient', models.CharField(help_text='Destinataire (email ou URL webhook)', max_length=500)),
                ('response', models.TextField(blank=True, help_text='Réponse du serveur (pour webhooks) ou erreur')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('backup_job', models.ForeignKey(blank=True, help_text='Job de backup associé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='backups.backupjob')),
                ('config', models.ForeignKey(help_text='Configuration utilisée pour envoyer la notification', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='backups.notificationconfig')),
                ('virtual_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='esxi.virtualmachine')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
