# Generated by Django 5.1.5 on 2025-11-19 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0012_add_notification_models'),
        ('esxi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OVFExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_location', models.CharField(help_text="Chemin de base de l'export", max_length=255)),
                ('export_full_path', models.CharField(blank=True, help_text="Chemin complet de l'export", max_length=512)),
                ('export_size_mb', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ovf_exports', to=settings.AUTH_USER_MODEL)),
                ('remote_storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ovf_exports', to='backups.remotestorageconfig')),
                ('virtual_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ovf_exports', to='esxi.virtualmachine')),
            ],
        ),
        migrations.CreateModel(
            name='VMBackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('full', 'Full Backup'), ('incremental', 'Incremental Backup')], default='full', max_length=50)),
                ('backup_location', models.CharField(help_text='Chemin de base de la sauvegarde', max_length=255)),
                ('backup_full_path', models.CharField(blank=True, help_text='Chemin complet de la sauvegarde', max_length=512)),
                ('backup_size_mb', models.FloatField(default=0)),
                ('snapshot_name', models.CharField(blank=True, help_text='Nom du snapshot créé', max_length=255)),
                ('snapshot_id', models.CharField(blank=True, help_text='ID du snapshot VMware', max_length=255)),
                ('vm_config_file', models.CharField(blank=True, help_text='Fichier .vmx de configuration', max_length=512)),
                ('vmdk_files', models.JSONField(default=list, help_text='Liste des fichiers VMDK sauvegardés')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('base_backup', models.ForeignKey(blank=True, help_text='Référence à la sauvegarde de base', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incremental_backups', to='backups.vmbackupjob')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vm_backups', to=settings.AUTH_USER_MODEL)),
                ('remote_storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vm_backups', to='backups.remotestorageconfig')),
                ('scheduled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vm_backup_jobs', to='backups.backupschedule')),
                ('virtual_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vm_backups', to='esxi.virtualmachine')),
            ],
        ),
    ]
