# Generated by Django 4.2.26 on 2025-12-04 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("esxi", "0002_emailsettings"),
        ("backups", "0019_add_replication_and_surebackup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vmreplication",
            name="source_server",
            field=models.ForeignKey(
                blank=True,
                help_text="Serveur ESXi source (auto-détecté depuis la VM)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replication_sources",
                to="esxi.esxiserver",
            ),
        ),
    ]
