# Generated by Django 5.2.8 on 2025-11-06 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ESXiServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('port', models.PositiveIntegerField(default=443)),
                ('connection_status', models.CharField(default='disconnected', max_length=50)),
                ('last_connection', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DatastoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('capacity_gb', models.FloatField()),
                ('free_space_gb', models.FloatField()),
                ('accessible', models.BooleanField(default=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datastores', to='esxi.esxiserver')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('power_state', models.CharField(max_length=50)),
                ('num_cpu', models.IntegerField()),
                ('memory_mb', models.IntegerField()),
                ('disk_gb', models.FloatField()),
                ('guest_os', models.CharField(max_length=255)),
                ('guest_os_full', models.CharField(max_length=255)),
                ('tools_status', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vms', to='esxi.esxiserver')),
            ],
        ),
    ]
