# Generated by Django 4.2.26 on 2025-12-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esxi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "smtp_host",
                    models.CharField(
                        default="smtp.gmail.com",
                        help_text="Serveur SMTP",
                        max_length=255,
                    ),
                ),
                (
                    "smtp_port",
                    models.PositiveIntegerField(
                        default=587, help_text="Port SMTP (587 pour TLS, 465 pour SSL)"
                    ),
                ),
                (
                    "smtp_username",
                    models.CharField(
                        blank=True, help_text="Nom d'utilisateur SMTP", max_length=255
                    ),
                ),
                (
                    "smtp_password",
                    models.CharField(
                        blank=True, help_text="Mot de passe SMTP", max_length=255
                    ),
                ),
                (
                    "smtp_use_tls",
                    models.BooleanField(default=True, help_text="Utiliser TLS"),
                ),
                (
                    "smtp_use_ssl",
                    models.BooleanField(default=False, help_text="Utiliser SSL"),
                ),
                (
                    "from_email",
                    models.EmailField(
                        blank=True,
                        help_text="Adresse email d'expédition",
                        max_length=255,
                    ),
                ),
                (
                    "admin_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email administrateur pour les notifications",
                        max_length=255,
                    ),
                ),
                (
                    "notify_backup_success",
                    models.BooleanField(
                        default=False, help_text="Notifier les sauvegardes réussies"
                    ),
                ),
                (
                    "notify_backup_failure",
                    models.BooleanField(
                        default=True, help_text="Notifier les échecs de sauvegarde"
                    ),
                ),
                (
                    "notify_surebackup_success",
                    models.BooleanField(
                        default=True,
                        help_text="Notifier les vérifications SureBackup réussies",
                    ),
                ),
                (
                    "notify_surebackup_failure",
                    models.BooleanField(
                        default=True,
                        help_text="Notifier les échecs de vérification SureBackup",
                    ),
                ),
                (
                    "notify_replication_failure",
                    models.BooleanField(
                        default=True, help_text="Notifier les échecs de réplication"
                    ),
                ),
                (
                    "email_notifications_enabled",
                    models.BooleanField(
                        default=False, help_text="Activer les notifications par email"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email Settings",
                "verbose_name_plural": "Email Settings",
            },
        ),
    ]
